[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 4

[[main]]
  identifier = "categories"
  name = "Categories"
  url = "categories"
  weight = 3

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"

[[main]]
  identifier = "gallery"
  name = "Gallery"
  url = "gallery"
    
[[main]]
  parent = "tags"
  name = "Tags"
  url = "tags"
  weight = 2

[[main]]
  parent = "gallery"
  name = "Photo"
  url = "gallery/photo"

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 1

[[main]]
  identifier = "showcase"
  name = "Showcase"
  url = "showcase"

[[main]]
  identifier = "publication"
  name = "Pub"
  url = "publication"